import os
import sys

# -- Project information -----------------------------------------------------
project = "PEST++"
copyright = "2024, PEST++ Development Team"
author = "PEST++ Development Team"
release = "5"

# -- General configuration ---------------------------------------------------
extensions = [
    "breathe",
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "myst_parser",
]

templates_path = ["_templates"]
# users_manual_processed.md is generated by preprocess_manual.py and pulled into users_guide.md
# with an {include}. Excluding it stops sphinx ALSO picking it up as a document in its own right
# - without this it is parsed twice and every one of the manual's ~270 section targets is
# defined twice, which makes each one an ambiguous cross-reference. The include still works:
# exclude_patterns governs document discovery, not reading a file.
exclude_patterns = ["_build", "_doxygen", "Thumbs.db", ".DS_Store",
                    "users_manual_processed.md"]

# -- Breathe configuration ---------------------------------------------------
# Path is relative to conf.py (i.e. docs/_doxygen/xml)
breathe_projects = {
    "pestpp": os.path.join(os.path.dirname(__file__), "_doxygen", "xml"),
}
breathe_default_project = "pestpp"
breathe_default_members = ("members", "undoc-members")

# -- HTML output -------------------------------------------------------------
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_logo = None

# Copy the users manual media folder into the HTML output so that
# image references in pestpp_users_manual.md resolve correctly.
# The pre-build step (or local setup) copies documentation/media/ -> docs/media/
# and Sphinx places it at _build/html/media/.

# -- MyST (Markdown support) -------------------------------------------------
myst_enable_extensions = ["colon_fence", "html_image"]
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}
